import jsPDF from 'jspdf';

/**
 * Generates a compliance report PDF for hiring fairness audit
 * @param {Object} auditData - Audit information
 * @param {Object} metrics - Bias detection metrics
 * @param {Object} org - Organization information
 * @returns {Object} jsPDF document object
 */
export function generateComplianceReport(auditData, metrics, org) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // PAGE 1 - COVER
  doc.setFillColor(15, 14, 13);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('FAIRLENS', 20, 40, { align: 'left' });

  doc.setFont('Playfair Display', 'bold');
  doc.setFontSize(28);
  doc.text('Hiring Fairness', 20, 70, { align: 'left' });
  doc.text('Compliance Report', 20, 90, { align: 'left' });

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(`Organization: ${org?.name || 'Unknown'}`, 20, 120);
  doc.text(`Hiring Cycle: ${auditData?.cycleName || 'N/A'}`, 20, 130);
  
  if (auditData?.startDate && auditData?.endDate) {
    const startDate = new Date(auditData.startDate).toLocaleDateString();
    const endDate = new Date(auditData.endDate).toLocaleDateString();
    doc.text(`Date Range: ${startDate} to ${endDate}`, 20, 140);
  }

  doc.setFontSize(10);
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(`Generated by FairLens on ${generatedDate}`, 20, 160);

  // Red divider
  doc.setDrawColor(201, 64, 10);
  doc.setLineWidth(2);
  doc.line(20, 170, pageWidth - 20, 170);

  doc.setFontSize(9);
  doc.text('CONFIDENTIAL — For Legal Review', 20, 185, { align: 'left' });

  // PAGE 2 - EXECUTIVE SUMMARY
  doc.addPage();
  yPosition = 20;

  doc.setTextColor(15, 14, 13);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('Executive Summary', 20, yPosition);
  yPosition += 12;

  // Fairness Health Score circle
  const scoreRadius = 15;
  const scoreX = 45;
  const scoreY = yPosition + 15;
  
  const score = calculateFairnessScore(metrics);
  let scoreColor;
  if (score >= 80) {
    scoreColor = '#1a6b3a'; // Green
  } else if (score >= 60) {
    scoreColor = '#8a5a00'; // Amber
  } else {
    scoreColor = '#c9400a'; // Red
  }

  const [r, g, b] = hexToRgb(scoreColor);
  doc.setFillColor(r, g, b);
  doc.circle(scoreX, scoreY, scoreRadius, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(score.toString(), scoreX, scoreY + 5, { align: 'center' });

  doc.setTextColor(15, 14, 13);
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Fairness', scoreX + 20, scoreY - 5);
  doc.text('Health Score', scoreX + 20, scoreY + 2);

  yPosition += 40;

  // Key Finding
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Key Finding:', 20, yPosition);
  yPosition += 6;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  const keyFinding = generateKeyFinding(metrics);
  const keyFindingLines = doc.splitTextToSize(keyFinding, pageWidth - 40);
  doc.text(keyFindingLines, 20, yPosition);
  yPosition += keyFindingLines.length * 5 + 5;

  // Compliance Status Table
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Compliance Status', 20, yPosition);
  yPosition += 8;

  const complianceStatuses = getComplianceStatuses(metrics);
  const tableData = complianceStatuses.map(status => [
    status.framework,
    status.status,
    status.exposure
  ]);

  doc.autoTable({
    startY: yPosition,
    head: [['Legal Framework', 'Status', 'Exposure']],
    body: tableData,
    margin: { left: 20, right: 20 },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { cellWidth: 40 },
      2: { cellWidth: 40 }
    },
    headStyles: {
      fillColor: [243, 240, 234],
      textColor: [15, 14, 13],
      fontStyle: 'bold'
    },
    bodyStyles: {
      fillColor: [255, 255, 255],
      textColor: [15, 14, 13]
    }
  });

  // PAGE 3 - LEGAL ANALYSIS
  doc.addPage();
  yPosition = 20;

  doc.setTextColor(15, 14, 13);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('Legal Analysis', 20, yPosition);
  yPosition += 12;

  // 2.1 Constitutional Exposure
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('2.1 Constitutional Exposure (Article 15 and 16)', 20, yPosition);
  yPosition += 7;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  const constitutionalFinding = generateConstitutionalFinding(metrics);
  const constLines = doc.splitTextToSize(constitutionalFinding, pageWidth - 40);
  doc.text(constLines, 20, yPosition);
  yPosition += constLines.length * 5 + 4;

  const constitutionalExposure = getExposureLevel(metrics.disparateImpactBySurname);
  doc.setFont('Helvetica', 'bold');
  doc.text(`Exposure: ${constitutionalExposure}`, 20, yPosition);
  yPosition += 8;

  // 2.2 SC/ST Prevention of Atrocities Act 1989
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('2.2 SC/ST Prevention of Atrocities Act 1989', 20, yPosition);
  yPosition += 7;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  const scstFinding = `Analysis of candidate selection patterns indicates ${getExposureLevel(metrics.disparateImpactBySurname)} exposure to SC/ST Act implications based on disparate treatment of candidates with varying demographic profiles.`;
  const scstLines = doc.splitTextToSize(scstFinding, pageWidth - 40);
  doc.text(scstLines, 20, yPosition);
  yPosition += scstLines.length * 5 + 4;

  doc.setFont('Helvetica', 'bold');
  doc.text(`Compliance Status: ${metrics.disparateImpactBySurname > 1.25 ? 'NON-COMPLIANT' : 'COMPLIANT'}`, 20, yPosition);
  yPosition += 8;

  // 2.3 Equal Opportunity Policy
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('2.3 Equal Opportunity Policy - Companies Act Amendment 2023', 20, yPosition);
  yPosition += 7;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  const eoPolicyFinding = `The hiring process demonstrates ${metrics.equalOpportunityDiff > 0.1 ? 'potential violations' : 'alignment'} with equal opportunity requirements under the Companies Act Amendment 2023.`;
  const eoLines = doc.splitTextToSize(eoPolicyFinding, pageWidth - 40);
  doc.text(eoLines, 20, yPosition);
  yPosition += eoLines.length * 5 + 4;

  doc.setFont('Helvetica', 'bold');
  doc.text(`Compliance Status: ${metrics.equalOpportunityDiff > 0.1 ? 'REVIEW REQUIRED' : 'COMPLIANT'}`, 20, yPosition);
  yPosition += 8;

  // 2.4 Digital Personal Data Protection Act 2023
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('2.4 Digital Personal Data Protection Act 2023', 20, yPosition);
  yPosition += 7;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('FairLens generates comprehensive documentation for all hiring decisions,', 20, yPosition);
  yPosition += 5;
  doc.text('ensuring compliance with data protection requirements and audit trails.', 20, yPosition);
  yPosition += 5;

  doc.setFont('Helvetica', 'bold');
  doc.text('Compliance Status: COMPLIANT', 20, yPosition);
  yPosition += 8;

  // 2.5 EU AI Act 2024
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('2.5 EU AI Act 2024', 20, yPosition);
  yPosition += 7;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('Applicable if company has EU operations. Assess with legal counsel.', 20, yPosition);
  yPosition += 5;

  doc.setFont('Helvetica', 'bold');
  doc.text('Compliance Status: ASSESS WITH LEGAL COUNSEL', 20, yPosition);

  // PAGE 4 - TECHNICAL FINDINGS
  doc.addPage();
  yPosition = 20;

  doc.setTextColor(15, 14, 13);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('Technical Findings', 20, yPosition);
  yPosition += 12;

  // Metrics table
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Bias Metrics', 20, yPosition);
  yPosition += 8;

  const metricsTableData = [
    ['Disparate Impact (College)', formatMetric(metrics.disparateImpactByCollege)],
    ['Disparate Impact (City)', formatMetric(metrics.disparateImpactByCity)],
    ['Disparate Impact (Surname)', formatMetric(metrics.disparateImpactBySurname)],
    ['Equal Opportunity Difference', formatMetric(metrics.equalOpportunityDiff)]
  ];

  doc.autoTable({
    startY: yPosition,
    head: [['Metric', 'Value']],
    body: metricsTableData,
    margin: { left: 20, right: 20 },
    columnStyles: {
      0: { cellWidth: 100 },
      1: { cellWidth: 60 }
    },
    headStyles: {
      fillColor: [243, 240, 234],
      textColor: [15, 14, 13],
      fontStyle: 'bold'
    }
  });

  yPosition = doc.lastAutoTable.finalY + 10;

  // Proxy Correlations Table
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Proxy Correlations', 20, yPosition);
  yPosition += 8;

  const proxyTableData = Object.entries(metrics.proxyCorrelations || {}).map(([key, value]) => [
    formatProxyName(key),
    (value * 100).toFixed(2) + '%'
  ]);

  if (proxyTableData.length > 0) {
    doc.autoTable({
      startY: yPosition,
      head: [['Proxy Variable', 'Correlation']],
      body: proxyTableData,
      margin: { left: 20, right: 20 },
      columnStyles: {
        0: { cellWidth: 100 },
        1: { cellWidth: 60 }
      },
      headStyles: {
        fillColor: [243, 240, 234],
        textColor: [15, 14, 13],
        fontStyle: 'bold'
      }
    });
    yPosition = doc.lastAutoTable.finalY + 10;
  }

  // Model Information
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Sample size: ${auditData?.candidateCount || 'N/A'} candidates`, 20, yPosition);
  yPosition += 5;
  doc.text(`Surrogate model accuracy: ${auditData?.modelAccuracy || 'N/A'}%`, 20, yPosition);
  yPosition += 5;
  doc.text('Note: Confidence intervals widen for groups under 30 candidates', 20, yPosition);

  // PAGE 5 - SIGNATURE PAGE
  doc.addPage();
  yPosition = 60;

  doc.setTextColor(15, 14, 13);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Signature & Approval', 20, yPosition);
  yPosition += 20;

  // HR Officer Signature line
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('HR Compliance Officer:', 20, yPosition);
  yPosition += 10;
  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(0.5);
  doc.line(20, yPosition, 80, yPosition);
  yPosition += 5;
  doc.setFontSize(8);
  doc.text('Signature', 20, yPosition);
  yPosition += 8;

  doc.line(100, yPosition - 13, 160, yPosition - 13);
  doc.text('Date', 100, yPosition);
  yPosition += 20;

  // Legal Reviewer Signature line
  doc.setFontSize(10);
  doc.text('Legal Reviewer:', 20, yPosition);
  yPosition += 10;
  doc.line(20, yPosition, 80, yPosition);
  yPosition += 5;
  doc.setFontSize(8);
  doc.text('Signature', 20, yPosition);
  yPosition += 8;

  doc.line(100, yPosition - 13, 160, yPosition - 13);
  doc.text('Date', 100, yPosition);
  yPosition += 30;

  // Disclaimer box
  doc.setFillColor(243, 240, 234);
  doc.rect(20, yPosition, pageWidth - 40, 50, 'F');
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Disclaimer', 25, yPosition + 5);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8);
  const disclaimerText = 'This report is audit documentation generated by FairLens. It is not legal advice and does not constitute legal certification of compliance. A qualified legal professional must interpret specific liability. FairLens is not liable for decisions made using this report.';
  const disclaimerLines = doc.splitTextToSize(disclaimerText, pageWidth - 50);
  doc.text(disclaimerLines, 25, yPosition + 12);

  return doc;
}

/**
 * Helper function to calculate fairness score (0-100)
 */
function calculateFairnessScore(metrics) {
  let score = 100;

  // Deduct for disparate impact
  if (metrics.disparateImpactBySurname > 1.25) score -= 30;
  else if (metrics.disparateImpactBySurname > 1.1) score -= 15;

  if (metrics.disparateImpactByCollege > 1.25) score -= 15;
  else if (metrics.disparateImpactByCollege > 1.1) score -= 8;

  if (metrics.disparateImpactByCity > 1.25) score -= 15;
  else if (metrics.disparateImpactByCity > 1.1) score -= 8;

  // Deduct for equal opportunity differences
  if (metrics.equalOpportunityDiff > 0.2) score -= 10;
  else if (metrics.equalOpportunityDiff > 0.1) score -= 5;

  return Math.max(0, Math.min(100, score));
}

/**
 * Helper function to generate key finding text
 */
function generateKeyFinding(metrics) {
  const disparateSurname = metrics.disparateImpactBySurname || 1.0;
  const disparateCollege = metrics.disparateImpactByCollege || 1.0;

  if (disparateSurname > 1.25) {
    return `The analysis reveals significant disparate impact (${(disparateSurname * 100 - 100).toFixed(0)}% difference) based on surname analysis, indicating potential constitutional violations under Article 15 and 16.`;
  } else if (disparateCollege > 1.25) {
    return `The hiring decisions show notable disparate treatment by educational background (${(disparateCollege * 100 - 100).toFixed(0)}% difference), suggesting potential systemic bias in evaluation.`;
  } else if (metrics.equalOpportunityDiff > 0.15) {
    return `The analysis indicates concerns regarding equal opportunity compliance with a difference of ${(metrics.equalOpportunityDiff * 100).toFixed(1)}% between groups.`;
  } else {
    return `The hiring process demonstrates general alignment with fairness standards across measured dimensions, with no significant disparities detected.`;
  }
}

/**
 * Helper function to get compliance statuses
 */
function getComplianceStatuses(metrics) {
  const baseStatus = metrics.disparateImpactBySurname > 1.25 ? 'NON-COMPLIANT' : 'COMPLIANT';
  const exposure = getExposureLevel(metrics.disparateImpactBySurname);

  return [
    { framework: 'Constitutional (Article 15 & 16)', status: baseStatus, exposure: exposure },
    { framework: 'SC/ST Prevention of Atrocities Act', status: baseStatus, exposure: exposure },
    { framework: 'Equal Opportunity Policy (2023)', status: metrics.equalOpportunityDiff > 0.1 ? 'REVIEW' : 'COMPLIANT', exposure: 'MEDIUM' },
    { framework: 'Data Protection Act 2023', status: 'COMPLIANT', exposure: 'NONE' },
    { framework: 'EU AI Act 2024', status: 'ASSESS', exposure: 'IF APPLICABLE' }
  ];
}

/**
 * Helper function to generate constitutional finding
 */
function generateConstitutionalFinding(metrics) {
  const disparateSurname = metrics.disparateImpactBySurname || 1.0;
  const exposure = getExposureLevel(disparateSurname);

  if (disparateSurname > 1.25) {
    return `Analysis reveals ${exposure} exposure under Article 15 (prohibition of discrimination on grounds of religion, race, caste, sex) and Article 16 (equality of opportunity in public employment) due to surname-based disparate impact of ${(disparateSurname * 100 - 100).toFixed(1)}%.`;
  } else if (disparateSurname > 1.1) {
    return `Analysis indicates ${exposure} exposure under constitutional provisions due to surname-based differences of ${(disparateSurname * 100 - 100).toFixed(1)}% in hiring outcomes.`;
  } else {
    return `Analysis shows ${exposure} exposure under constitutional provisions based on measured metrics.`;
  }
}

/**
 * Helper function to determine exposure level
 */
function getExposureLevel(metric) {
  if (metric > 1.5) return 'HIGH';
  if (metric > 1.25) return 'MEDIUM';
  if (metric > 1.1) return 'LOW';
  return 'NONE';
}

/**
 * Helper function to format metric values
 */
function formatMetric(value) {
  if (typeof value === 'number') {
    return value.toFixed(3);
  }
  return value || 'N/A';
}

/**
 * Helper function to format proxy names
 */
function formatProxyName(key) {
  const names = {
    surname: 'Surname Pattern',
    college_tier: 'College Tier',
    city_tier: 'City Tier',
    gaps: 'Employment Gaps',
    company_tier: 'Company Tier',
    language_score: 'Language Complexity'
  };
  return names[key] || key;
}

/**
 * Helper function to convert hex to RGB
 */
function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? [
    parseInt(result[1], 16),
    parseInt(result[2], 16),
    parseInt(result[3], 16)
  ] : [0, 0, 0];
}
